### ISSUE TITLE
IDNA / UTS #46 "should" requirements (Bidi and Joiners)

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#110]
https://url.spec.whatwg.org/#idna refers (through the “Unicode ToAscii” and “Unicode ToUnicode” algorithms) to http://www.unicode.org/reports/tr46/#Processing and rely on the error flag.

>  The following steps, performed in order, successively alter the input domain_name string and then output it as a converted Unicode string, plus a flag to indicate whether there was an error.

This it turns refers to Section 4.1 http://www.unicode.org/reports/tr46/#Validity_Criteria which has a series of “must” requirements. For example:

> The label must be in Unicode Normalization Form NFC.

This section also has a subsection 4.1.2 http://www.unicode.org/reports/tr46/#Right_to_Left_Scripts

>  In addition, the label **should** meet the requirements for right-to-left characters specified in the Right-to-Left Scripts document of [IDNA2008], and for the CONTEXTJ requirements in the Protocol document of [IDNA2008]. It is strongly recommended that Unicode Technical Report #36, Unicode Security Considerations [UTR36] and Unicode Technical Standard #39, Unicode Security Mechanisms [UTS39] be consulted for information on dealing with confusables, and for characters that should be excluded from identifiers. Note that the recommended exclusions are a superset of those in [IDNA2008]. 

Note “should” (emphasis added) and “strongly recommended” rather than “must”.

If the URL Standard is to define interoperable algorithms, I think it needs to define in which requirements Section 4.1.2 sets the error flag.

(Related: https://github.com/servo/rust-url/issues/179)

**Comment by annevk** [comment]
Interesting, yeah, I don't think that should be enforced. We should probably make this configurable in the IDNA standard.

I noticed the line you quoted mentioned transitional processing. It seems Gecko is successfully shipping non-transitional processing these days. Perhaps Servo can do so too? And maybe the URL Standard should start requiring that? It's still rather contentious whether it's a good idea though...

**Comment by SimonSapin** [comment]
> I noticed the line you quoted mentioned transitional processing. It seems Gecko is successfully shipping non-transitional processing these days. Perhaps Servo can do so too? And maybe the URL Standard should start requiring that? It's still rather contentious whether it's a good idea though...

What do other browsers do?

CC @valenting

**Comment by annevk** [comment]
@SimonSapin all other browsers do transitional as far as I know. See https://bugzilla.mozilla.org/show_bug.cgi?id=1218179 for details.

**Comment by achristensen07** [comment]
WebKit just switched to non-transitional processing and added tests verifying that we do Bidi checks and ContextJ checks.  We don't do ContextO checks because nobody else does yet. See https://bugs.webkit.org/show_bug.cgi?id=144194

**Comment by terinjokes** [comment]
Just an update on user-agent support from a random user who happened to Googlewhack to this thread (edit: sorry, it seems to have gone a tad off topic): 

* :white_check_mark: As mentioned by @achristensen07, WebKit seems to be using some form of non-transitional processing. It looks like this has been picked up by Safari Technical Preview as well.
* :white_check_mark: Firefox has landed this in stable at some point in 2016.
* :red_circle: Chrome's most recent ticket [505262](https://bugs.chromium.org/p/chromium/issues/detail?id=505262&thanks=505262&ts=1435488604) is currently `WONTFIX` and they might reconsider at some point in 2017.
* :red_circle: Edge hasn't had an update in a year now [6818768](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6818768/).

In a quick check of development environments I've used in the last 24 hours (transparent support via the language's HTTP interfaces are untested):
* :white_check_mark: Node.js has been using non-transitional IDN since has least 0.10.41 (the oldest I have installed).
* :large_orange_diamond: PHP supports since 5.4, though IDN2003 is still the (deprecated) default. One probably wants:

  ```php
  idn_to_ascii('gießen.xx', IDNA_NONTRANSITIONAL_TO_ASCII | IDNA_CHECK_BIDI | IDNA_CHECK_CONTEXTJ, INTL_IDNA_VARIANT_UTS46);
  ```
* :white_check_mark: In Go, `golang.org/net/x/idna` does non-transitional processing.  Interestingly, the support in the `github.com/miekg/dns/idn` package also does non-transitional processing for the inputs I've tested, despite the documentation saying it implements IDN2003.

**Comment by annevk** [comment]
There's more recent tickets filed by myself: https://bugs.chromium.org/p/chromium/issues/detail?id=694157 and https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11009037/.

**Comment by terinjokes** [comment]
@annevk Thanks! I missed those while Googling.

**Comment by annevk** [comment]
See also #263 for issues with Python that may well exist in other implementations. Interoperability issues for everyone.

**Comment by annevk** [comment]
FWIW, I'm pretty sure CONTEXTJ must be false, otherwise 👩‍⚕️ cannot be represented whereas that works fine in user agents. (As seen in http://www.unicode.org/reports/tr46/tr46-18.html#Validity_Criteria.)

**Comment by annevk** [comment]
Hmm, maybe that's wrong. Safari definitely doesn't seem to do the same thing as Firefox for CONTEXTJ though per https://trac.webkit.org/changeset/208902/webkit it should? @achristensen07 any insights? I kinda thing we should allow CONTEXTJ if we allow emojis for subdomains. Banning a subset of emojis seems a little weird.

**Comment by annevk** [comment]
http://www.unicode.org/reports/tr46/proposed.html#Processing has these now as input flags so they're no longer should requirements. My limited testing shows CheckBidi should be true. For CheckJoiners the results are unclear. Input welcome.

**Comment by annevk** [comment]
And in case it wasn't clear, Nontransitional_Processing started to be used in the URL Standard since #239.

**Comment by annevk** [comment]
It seems that most user agents enforce CheckJoiners if I don't check the more problematic emoji case. So I'll go with that.
