### ISSUE TITLE
Trailing dot and origin compuation

### ISSUE THREAD

**Issue by timdream** [whatwg/url#132]
The current browser implementations consider `github.com.` and `github.com` different origins.

This is correct because RFC1034 specifies the later "relative domain" allow DNS to resolve it against search domains, and it is possible that `github.com` resolves to `github.com.corp.mycorp-inc.net.` on my corp network (while the browser would still showing me connected to `github.com`).

GitHub, in this case, will issue a 301 redirection if you attempt to access `https://github.com./`. Google does not do that, however.

I wonder if it is worthy to explicitly explain that in the URL spec?

**Comment by annevk** [comment]
I guess we could mention it. Though it seems like something that follows from them being different hosts, not from them computing to different origins (since different hosts means different origins). So if we mention it, it should go in the host/domain section.

**Comment by annevk** [comment]
I created a PR, would appreciate your review.

**Comment by timdream** [comment]
> I created a PR, would appreciate your review.

@annevk Looks good. Thanks for follow up. I will probably look into how SSL works next...

**Comment by sleevi** [comment]
What do you mean how SSL works? RFC6125 covers name validation, but it has
no relation to the Origin or URL specs.

Unlike names in URLs (whose omission of a trailing dot may result in domain
suffix search), the names expressed in a certificate are always fully
qualified and have an implicit trailing dot.

Whether or not an implementation recognizes is implementation dependent,
and neither RFC6125 nor the URL spec would likely alter browser behavior
here, since the name matching is typically not part of the "browser"
managed side (instead it's part of the TLS library  / OS)

**Comment by timdream** [comment]
@sleevi Thanks for spelling out the answer for me quite nicely. I was meant to say I intend to find these answers out myself...

**Comment by annevk** [comment]
@sleevi FWIW, I think I somewhat disagree with your views on layering. Or at least which standards apply where, but it also doesn't matter much short term or for the resolution of this issue.
