### ISSUE TITLE
unicode fragments

### ISSUE THREAD

**Issue by achristensen07** [whatwg/url#150]
Right now there is a note: "Unfortunately not using percent-encoding is intentional as implementations with majority market share exhibit this behavior."

I think we should change "Append c to url’s fragment." to at least "If url’s scheme is a special scheme, append c to url’s fragment.  Otherwise, append the result of running UTF-8 percent encode with the simple encode set on c" or something similar.  

Right now Firefox and Safari percent-encode non-ASCII characters in the fragment.  Chrome percent-encodes non-ASCII characters in the fragment if the scheme is not a special scheme.  Edge does not percent-encode any non-ASCII characters in the fragment.

This change is needed to continue to support percent-encoding non-ascii characters after a '#' in a data URL, which works in Safari, Chrome, and Firefox.

**Comment by achristensen07** [comment]
Ideally, I think we'd all just switch to percent encoding all non-ASCII characters in all fragments so the output of URL parsing is always ASCII.  Would everyone be willing to make such a change?

**Comment by annevk** [comment]
@valenting? I think @dbaron also wanted us to always percent-encode, to keep URLs "ASCII safe" and easier to copy-and-paste (due to whitespace and such).

**Comment by valenting** [comment]
I support percent encoding all characters in the hash. It turns out percent encoded strings are much easier to manage and parse.

**Comment by annevk** [comment]
It seems HTML already decodes fragment identifiers in https://html.spec.whatwg.org/multipage/browsers.html#the-indicated-part-of-the-document so presumably that would keep working.

But I suspect there might be websites that depend on fragment not being encoded?

@achristensen07 did you verify that all APIs for URLs in WebKit return the URL with the fragment encoded as well? Or in order to have URLs with the fragment encoded would we need to add special casing to APIs?

**Comment by achristensen07** [comment]
In WebKit, the fragments are encoded/serialized as they are parsed, so there is no time in which there will be an unencoded fragment in a URL

**Comment by annevk** [comment]
@achristensen07 that's understood, but my question is if there's any APIs such as `location.hash` that might yield them as unencoded (essentially with the accessor doing its conversion).

**Comment by achristensen07** [comment]
I do not think we ever percent-decode fragments in WebKit.  Going to the indicated part of the document with percent-encoded fragments or non-ASCII fragments which we percent encode doesn't work in WebKit right now, which we need to fix.

**Comment by dbaron** [comment]
> I think @dbaron also wanted us to always percent-encode, to keep URLs "ASCII safe" and easier to copy-and-paste (due to whitespace and such).

In particular, the argument I made was in [Mozilla bug 1148861](https://bugzilla.mozilla.org/show_bug.cgi?id=1148861) (comment 0 and comment 25).

**Comment by annevk** [comment]
So Gecko seems to be encoding too (although the address bar decodes). So that leaves Chrome and Edge. @foolip who's a good contact for URL parsing in Chrome?

**Comment by sleevi** [comment]
I'm still lurking watching these bugs, @annevk , at least for our low-level implementation (and how it relates to URL bar). When it get's to Blink side, @mikewest is good to poke just to make sure I don't stuff it all up :)

**Comment by foolip** [comment]
Thanks @sleevi. @sof has also poked a bit at the Blink-side URL.

**Comment by annevk** [comment]
@sleevi I guess the question is then whether you'd consider always encoding fragments. (Or is that already happening and is the Blink side doing magic in the API layer?)

**Comment by sleevi** [comment]
@annevk Yeah, I'm planning on looking into this today and trying to get an answer. I seem to recall that it's similar to Gecko, and so I suspect our URL substrate is decoding, and any encoding would need to be done at the Blink glue to that (the KURL and bindings side). On the upside, it makes it easier to change when it would only affect Chrome (our URL code is shared with a growing number of Google products due to Cronet embedding), the downside is it may require a more extensive audit of where we expose those URLs to a web-visible form.

I'm not hearing a request to change address bar behavior, but did I misunderstand the remarks re: FF? My gut is that it seems to make sense to change that too, to ensure authors aren't going to copy/paste?

**Comment by annevk** [comment]
The address bar is a hard problem. If we always show everything encoded, we basically make it useless for some set of pages and people, e.g., Wikipedia articles with titles in Kanji visited by folks that can read Japanese. On the other hand, I don't think most people should really be looking at the address bar beyond the domain (and the rest can be hidden until you need to copy), but folks are going to disagree on that one and only Safari is really that far ahead right now.

There's also the aspect that we cannot dictate the address bar since it's UX. And you could potentially show decoded, but copy encoded, etc. I think for this issue we should consider it out-of-scope, and just consider the effects we can directly observe through JavaScript and following links in documents.

**Comment by annevk** [comment]
@sleevi any update? I'm inclined to go with always encoding the fragment since it would be the most consistent (URL members would only ever contain ASCII) and it appears that's what Firefox and Safari get away with.

**Comment by annevk** [comment]
I created a PR to change the specification here. I'd appreciate review. @achristensen07 do you know if this is already tested? I can change the tests.

**Comment by annevk** [comment]
FWIW, I started working on a patch for the tests and I noticed that Firefox has a few differences from my proposed change. It does not seem to drop U+0000 and it seems to preserve and encode newline and tab code points. Not sure that's what we want to keep given what we specified for other setters.

**Comment by achristensen07** [comment]
This is tested by these existing tests:
Parsing: <#β> against <http://example.org/foo/bar>
Parsing: <http://www.google.com/foo?bar=baz# »> against <about:blank>
Parsing: <data:test# »> against <about:blank>

**Comment by annevk** [comment]
https://github.com/w3c/web-platform-tests/pull/4298 has an update to the tests. I want to be sure though about what we want to encode, although I guess this change is still a step in the right direction so maybe we should make it regardless.

@valenting thoughts? Should we encode spaces as well? Is it okay to drop U+0000?

**Comment by valenting** [comment]
Right now Firefox drops \r\n\t in the URL constructor, and trims U+0000 to U+0020.
In the setters we encode all C0-and space characters. This is true for pathname, search and hash.
I don't have any preference about this, but we should at least try to be consistent.

**Comment by achristensen07** [comment]
Chrome and Safari don't encode spaces.  I propose using the simple encode set

**Comment by annevk** [comment]
@valenting the consistency we have now is that \r\n\t are always dropped. And trimming of U+0000 to U+0020 happens only for the full URL (not setters). Note that it should also happen for `<a>` and such, not just the URL constructor.

The main problem with not encoding spaces is that it's harder to copy-and-paste those URLs and drop them elsewhere. Since most tooling assumes URLs do not contain spaces.

Anyway, if the test changes look okay I suggest we land this and then if there are still concerns we can fiddle with the details in a new issue.

**Comment by valenting** [comment]
👍

**Comment by zcorpan** [comment]
Related issue https://github.com/whatwg/url/issues/125

**Comment by annevk** [comment]
Thanks @zcorpan, we can use that as the follow up for spaces.
