### ISSUE TITLE
Something is causing the </main> to be closed prematurely

### ISSUE THREAD

**Issue by domenic** [whatwg/url#190]
Compare the source of url.spec.whatwg.org with, e.g., infra.spec.whatwg.org. It appears the `</main>` gets closed somehow early on URL. Maybe because the `<pre>` blocks at the bottom instead of at the top?

**Comment by annevk** [comment]
Seems alright? Index is not part of the main content...

**Comment by domenic** [comment]
Yeah, but it's different on this spec from all the others; something is going wonky, I assume on this spec.

**Comment by annevk** [comment]
DOM and Storage are the same as this document. DOM has `<pre>` blocks at the top.

**Comment by domenic** [comment]
I guess maybe time to summon @tabatkins for some help diagnosing. In some WHATWG specs the `<main>` element gets closed before the indices (e.g. URL, DOM, and Storage), and in others it gets closed after the indices (e.g. Streams and Infra). This is presumably due to some vagaries of Bikeshed's HTML parser?

**Comment by tabatkins** [comment]
Nope, this is due to the way Infra/URL are written. URL is getting the standard treatment; the indexes are appended to `<body>`, so after the `<main>` is closed.  Infra specially suppresses generation of several indexes, and specially includes one of the indexes before the Acks section, so there's nothing after the `<main>` element.

In other words, Infra is the outlier, not URL, and it appears to be intentional on Anne's part.

**Comment by domenic** [comment]
I think I see. So the problem is that `<div data-fill-with=references></div>` should probably go after the acknowledgments?

**Comment by tabatkins** [comment]
I mean, it's not a problem.  But if you want to match the structure of the other specs, just remove it entirely; it'll automatically get appended to `<body>`.

(It's also quite weird that the Index is being suppressed - that seems particularly useful for a spec whose entire purpose in life is to define terms for other specs to use.)
