### ISSUE TITLE
URLUtilsReadOnly members no longer link to their definitions

### ISSUE THREAD

**Issue by annevk** [whatwg/url#29]
@tabatkins URLUtils and URLUtilsReadOnly in https://url.spec.whatwg.org/#api share the same definitions. How do I make sure they both point to the same link?

**Comment by tabatkins** [comment]
I'm not quite sure what you mean.  Do you mean that you want links like `{{URLUtilsReadOnly}}` to link to the `{{URLUtils}}` interface, or things like getting the IDL for URLUtilsReadOnly to point to the attribute definitions you've made for URLUtils?

If the latter, which I *think* is what you mean, then you just need to define that the definition is `for` both of them, like `for="URLUtils, URLUtilsReadOnly"`.

**Comment by annevk** [comment]
For some reason I was using `dfn-for`, but either seems to work fine with that syntax. Thanks. It's a bit weird semantically that any references to that attribute need to pick one and cannot list both, but I guess that does not really matter.

**Comment by tabatkins** [comment]
`for` goes directly on `<dfn>` or `<a>`; if you're putting it on an ancestor (to make it apply to all the dfn/links in the container) you have to specify whether it's `dfn-for` or `link-for`, because I can't tell automatically.  (Both are just shorthands for the *real* attributes `data-dfn-for` or `data-link-for`, which I auto-expand for you.) (It's of course valid to use `dfn-for` or `link-for` directly on a dfn/a; it's just longer than necessary.)

Agree that it's sometimes a little weird that a ref has to pick one or the other to refer to, but it's a corner-case that I don't feel is important enough to address (not to mention it introduces a new error-case where you say a link is for two definitions, which are assumed to be identical, but they're actually different now).
