### ISSUE TITLE
"append the empty string to url’s path." is confusing

### ISSUE THREAD

**Issue by Hixie** [whatwg/url#295]
https://url.spec.whatwg.org/commit-snapshots/488c459d9e4245a3f6bf087e7dcd2c7e91487ac5/#url-parsing

> append the empty string to url’s path.

It would be nice if the text explained why we are doing this apparently pointless step.

**Comment by TimothyGu** [comment]
AFAICT a [URL's path](https://url.spec.whatwg.org/commit-snapshots/488c459d9e4245a3f6bf087e7dcd2c7e91487ac5/#concept-url-path) is a [list](https://infra.spec.whatwg.org/#list), so appending an empty string to the path is equivalent to transforming `/foo` to `/foo/`

**Comment by Hixie** [comment]
This doesn't seem to be documented anywhere.

Also, consider the effect of parsing `/././././`.

**Comment by TimothyGu** [comment]
> Also, consider the effect of parsing `/././././`.

The first `/` will be parsed in one of the states other than path state, but after processing that character the state will be switched to path state.

The first `.` enters the second branch of path state, and _buffer_ is now `.` since it doesn't need to be encoded.

The second `/` will trigger the first branch in path state, but inside that branch it will skip directly to step 5, and url's path is not changed at all.

Repeat the last two steps for all code points in that input.

After parsing the last `/`, _c_ is the EOF code point, and since _buffer_ is empty, branch 1, step 4 of path state will be taken. An empty string is appended to url's path. And thus ends the state machine.

So in the end the input results in url's path being a list containing a single empty string, which returns `/` in the [URL serialization](https://url.spec.whatwg.org/commit-snapshots/488c459d9e4245a3f6bf087e7dcd2c7e91487ac5/#concept-url-serializer) algorithm.

**Comment by Hixie** [comment]
Sorry I meant `/../../../../../..`

**Comment by TimothyGu** [comment]
That has the same result as just a `/`, as they will chiefly go through step 2:

> 2. If _buffer_ is a double-dot path segment, shorten _url_’s path, and then if neither _c_ is U+002F (/), nor _url_ is special and _c_ is U+005C (\), append the empty string to _url_’s path.

where [shorten a URL's path](https://url.spec.whatwg.org/#shorten-a-urls-path) is specified to only remove the last item from the path if the path is not empty.

After the first `/`, path is still empty.

After the first set of `../`, path is shortened, but since it was empty before there is no change to path at all.

Repeat the this process, and when _c_ is the EOF code point, _buffer_ is `..`, _url_'s path is still empty. Step 2 first shortens the path (again, it remains empty), but since _c_ is not `/` or `\` an empty string is added to the path after shortening.

So in the end we get a path with one element, the empty string.

Which part is confusing? The name to "shorten a _url_’s path" when it is really "shorten path if possible"?

**Comment by Hixie** [comment]
I see.

I think maybe what's confusing is that there's no text explaining that when you get to this part, usually you'll have a `/` character. Basically, as a reader I'm going to do "branch prediction", and the way it's phrased makes it sound like the likely branch is to append.

**Comment by GPHemsley** [comment]
> If buffer is a double-dot path segment, shorten url’s path, and then if neither c is U+002F (/), nor url is special and c is U+005C (\), append the empty string to url’s path.

This whole line is confusing to me.

There's a combination of inline conditionals and inline actions, and it's really not clear what happens when.

Is there a reason this can't be broken out into a full list with clear actions and conditionals?
