### ISSUE TITLE
EOF after stand-alone drive-letter. 

### ISSUE THREAD

**Issue by alwinb** [whatwg/url#304]
The reference implementation currently parses `C|` against `file://host/dir/file` as `file://host/dir/C|`. 

Against the same base URL, 
* `C|` is parsed as `file://host/dir/C|` 
* `C|#` is parsed as `file:///C:#`
* `C|?` is parsed as `file:///C:?`
* `C|/` is parsed as `file:///C:/`
* `/C|` is parsed as `file:///C:`
* etc,

I am not (yet) sure if this is according to the current specification or an issue with the reference implementation. I would propose changing this behaviour to have `C|` yield `file:///C:`.

**Comment by rmisev** [comment]
It's the issue of current specification. It looks like the cause is a logic error in the [**file state**](https://url.spec.whatwg.org/commit-snapshots/488c459d9e4245a3f6bf087e7dcd2c7e91487ac5/#file-state) of **basic URL parser**. The base's path is copied, because `C|` satisfies the condition (remaining in this case is `|`):
> - remaining consists of one code point

I will try to fix it.
