### ISSUE TITLE
URL#searchParams#delete and "?" delimiter

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#332]
In https://github.com/w3c/web-platform-tests/pull/6445#issuecomment-313391675 we are suggesting that this should be true:

```js
const url = new URL("http://host/?param");
url.searchParams.delete("param");
url.href;  //-> http://host/?
```

I cannot see a valid top-level reason to *preserve* the trailing delimiter when the user of `URL` has chosen to make a mutation.

**Comment by annevk** [comment]
@TimothyGu @achristensen07 I'm inclined to fix this given the surprise in both the Chrome and Firefox bugs. That would mean WebKit has to change its behavior. Though I think Firefox should probably still change to remove the question mark when you remove a non-existent parameter.

My proposal would be to change https://url.spec.whatwg.org/#concept-urlsearchparams-update so that if the serialization is the empty string we set query to null.

**Comment by TimothyGu** [comment]
@annevk Alright. I'd still slightly prefer Firefox's behavior over Chrome's, but I'm fine with the path of least resistance, whatever that is.

And as one more data point, Node.js already follows Chrome's behavior after https://github.com/nodejs/node/issues/10480.

**Comment by annevk** [comment]
PR up. Will need to file bugs against Firefox (likely just update https://bugzilla.mozilla.org/show_bug.cgi?id=1379113) and Safari. (Edge doesn't support URLSearchParams yet.)

https://bugs.chromium.org/p/chromium/issues/detail?id=740048 can be closed if this is approved.

**Comment by achristensen07** [comment]
I agree with this conceptually and have changed WebKit in https://bugs.webkit.org/show_bug.cgi?id=174465

**Comment by annevk** [comment]
Thanks @achristensen07 and @stevenvachon for pushing this!
