### ISSUE TITLE
duplicates keys when calling `.keys()`

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/url#444]
Why dose `keys()` not return uniq keys?

```js
var q = new URLSearchParams('a=1&a=2')
var keys = Array.from(q.keys()) // ['a', 'a']
```

loop over all keys and doing something with them would run twice
```js
var q = new URLSearchParams('a=1&a=2')

for (let key of q.keys()) {
  console.log(q.getAll(key)) // logs ['1', '2'] twice 
}
```

Annoying solution

```js
var q = new URLSearchParams('a=1&a=2')

for (let key of new Set(q.keys())) {
  console.log(q.getAll(key)) // logs ['1', '2'] once 
}
```

**Comment by annevk** [comment]
`keys()`, `forEach()`, etc. are all derived from the same IDL construct. Is there precedent for those returning a different number of things?

**Comment by GPHemsley** [comment]
Aren't there numerous server-side (and possibly client-side) implementations that support repeating keys as a way to specify an array value? I don't think we can make the assumption that identical keys can be collapsed like an array/dict in other places. (Or do we already do that?)

I would expect the URL search params to be treated moreso like a list of pairs rather than an array/dict.

**Comment by jimmywarting** [comment]
> I would expect the URL search params to be treated moreso like a list of pairs rather than an array/dict.

Kinda makes since when you mention it...
Notices that FormData also treats it the same way as URLSearchParams dose

anyhow it was just a question and i just wondered if it was intentially or not
