### ISSUE TITLE
Formatting conventions

### ISSUE THREAD

**Issue by cvrebert** [whatwg/url#47]
The formatting conventions used in this spec seem to be different (and slightly less informative) than those of some of the other specs; for example (taking WHATWG HTML as gospel):
- ``%`` or `0x22` vs. `0x2F (ASCII %)`
- `"%"` vs. `U+0025 PERCENT SIGN (%)`

Would you be open to pull requests changing the former to the latter?

**Comment by annevk** [comment]
I think the HTML style is too verbose and doesn't work well for specifications such as Fetch (which needs to express long byte sequences as strings for readability). I would be okay with changes, but I'm not entirely sure what style would be best. 

For single units mentioning both the number and appearance seems fine (not sure about name), but once you have a sequence of them that gets hairy. And if you don't do it for a sequence, why would do it for a single unit?

**Comment by cvrebert** [comment]
> which needs to express long byte sequences as strings for readability
> [...]
> but once you have a sequence of them that gets hairy

Fair points.

> And if you don't do it for a sequence,

The awkwardness seems a reasonable enough justification for avoiding it for sequences, imho.

> why would do it for a single unit?

Well, right now the spec isn't consistent in how it formats single units, which is mildly annoying. For example:
* `code points U+0020, '"', "#",`
* ``Replace any `+` in name and value with 0x20.``

Mentioning both the number and the appearance for single units would at least avoid inconsistency in this particular respect. And I think seeing e.g. "space" as opposed to only "U+/0x 20" makes it slightly easier to understand what the spec is doing semantically when reading through it.

**Comment by annevk** [comment]
I would be open to using ␠ (U+0020) and ␠ (0x20) for the control character cases. See https://en.wikipedia.org/wiki/Unicode_control_characters#Control_pictures for a table of them. Maybe that makes them slightly less awkward to read.

**Comment by annevk** [comment]
Where the specification lists ranges we could perhaps also have something similar: "A" (U+...) to "Z" (U+...), inclusive. But perhaps since ranges are typically given a name that's not necessary.

**Comment by annevk** [comment]
Maybe still use " and ` though around ␠ to indicate code point vs byte. It's still a bit weird as we would not use ␠ in "two words" so maybe " " is good enough? And we'd only use those for the more hairy control cases?

**Comment by annevk** [comment]
@domenic should we make Infra say something about this?

**Comment by zcorpan** [comment]
How about this...
```
"<code title="U+0020"> </code>"
`<code title="0x74 0x77 0x6F 0x20 0x77 0x6F 0x72 0x64 0x73">two words</code>`
```

**Comment by annevk** [comment]
@zcorpan what would you do for U+000A or 0x0A? Part of the problem is code points that are not human-readable.

**Comment by zcorpan** [comment]
Control pictures for C0 other than space, both for single code point/byte and sequence.

**Comment by domenic** [comment]
I think Infra should cover the formatting conventions for code points. In fact, it already does, saying

> The code point rendered as 🤔 is represented as U+1F914.
>
> When referring to that code point, we might instead say "U+1F914 THINKING FACE (🤔)", instead of just "U+1F914", to provide extra context.

For bytes, it only gives a notation for byte sequences, otherwise expecting you to use the 0x20 form always:

> A byte is a sequence of eight bits, represented as a double-digit hexadecimal number in the range 0x00 to 0xFF, inclusive. 

It sounds like we have a few proposals to extend this. Let me summarize what I see as the most straightforward proposals, mixing in a few of my own by analogy:

- For code points:
  - Allow also the form "U+1F914 (🤔)". Seems fine.
  - Allow the form "🤔". I'm not a fan; this is ambiguous with a length-1 string containing the single code point.
  - For control characters, allow the form "U+0020 (␠)". I'm not a huge fan, since ␠ is actually U+2420.
  - Allow control characters inside strings in the form "abc␠def". Maybe this is OK, with appropriate verbiage in Infra explaining how to reinterpret certain characters in strings.
- For bytes
  - Allow the analogous form "0x2F SOLIDUS (%)". Not sure this is a good idea since aren't those names (like SOLIDUS) about code points, not bytes? 
  - Allow also the form "0x2F (%)". Probably fine.
  - Allow also the form \`%\`. Again ambiguous with the length-1 byte sequence...
  - Allow also the form "0x20 (␠)". Maybe less of a problem than for code points, since there is no single byte corresponding to U+2420?
  - Allow control characters inside byte sequences in the form \`abc␠def\`. Probably OK, with appropriate verbiage in Infra.

**Comment by annevk** [comment]
It has taken close to two years, but this has now a pull request (and a solution that's standardized across WHATWG Standards).
