### ISSUE TITLE
Forbidden host code points should include all C0 controls & U+007F

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/url#627]
Right now, [forbidden host code points](https://url.spec.whatwg.org/#forbidden-host-code-point) only includes U+0000 NULL and ASCII whitespaces from the C0 controls range. However, there seems to be no good reason to allow the other unprintable characters. Right now according to spec, `new URL('https://a\u0002b.com')` parses with `u.hostname === 'a\u0002b.com'`, which deviates from what a user might expect from a URL parser.

Most implementations agree with this assessment:

* Chrome and Go forbid C0 controls and `\u007F`, whether encoded or not
* Firefox forbids C0 controls verbatim, as well as `%00`–`%1F` and `%7F`. It allows `\u007F`.
* curl forbids C0 controls and `\u007F`, as well as `%00`–`%1F`. It allows `%7F`.
  * This is the dual of Firefox's behavior.
* Safari follows current spec.
* Python and Ruby accepts any percent-encoded characters in hosts
* Node.js legacy parser breaks when it sees any control character (percent-encoded or not) in hosts (it tries to add a `/` before the character or `%`)

I propose Chrome's behavior as it seems more consistent than Firefox or curl.

**Comment by valenting** [comment]
> Interestingly, in Firefox `new URL('https://a\u0007f.com')` 

That's because that is equivalent to:
`new URL("https://a" + String.fromCodePoint(0x07) + "f.com")` 🙂

**Comment by achristensen07** [comment]
🙂
I implemented this with tests at https://bugs.webkit.org/show_bug.cgi?id=232034

**Comment by TimothyGu** [comment]
@achristensen07 `new URL('https://a\u0007f.com')` is `a` U+0007 `f`, while `'a' + String.fromCodePoint(0x7F)` is `a` U+007F.

I guess I was wrong in my initial post (which I've just updated): Firefox forbids `%00`–`%1F`, `%7F`, and `\u0000`–`\u001F`. It does not forbid `\u007F`. Chrome forbids all of these.

I propose that we follow Chrome here as it's more consistent.

**Comment by annevk** [comment]
As pointed out by @achristensen07 in the WebKit bug one problem here might be non-special URLs.

I suspect we might not want to have things result in failure there as that would end up with things throwing that currently do not throw in either Chrome or Firefox.

That would be a further argument to fix #319 and probably have two separate constants. Thoughts? Anyone up for fixing this in the spec?

**Comment by alwinb** [comment]
The standard currently allows any string to be used as an opaque-host, if appropriately percent-encoded. 
Isn't it a bit strange to add a special case for only the percent-encoded-bytes that decode to C0 and DEL codepoints?

I had a look at making the change, but it turns out to be more complex than anticipated, of course :/

**Comment by annevk** [comment]
I'm not sure I understand the question.

**Comment by alwinb** [comment]
If I understood the proposal correctly, percent-encoded control code points in the hosts would cause the parser to fail. 

If that is extended to opaque hosts as well, that would mean that e.g. `sc://a%01` would fail, even though, e.g. `sc://a%35` does not. (`%35` decodes to `#`).

I think it is better to allow any percent-encoded bytes in opaque hosts.

**Comment by annevk** [comment]
As I wrote in https://github.com/whatwg/url/issues/627#issuecomment-948348158 I think we don't want to extend these requirements to opaque hosts.

**Comment by alwinb** [comment]
Thanks, excellent!

> I suspect we might not want to have things result in failure there as that would end up with things throwing that currently do not throw in either Chrome or Firefox.

Note though, that Chrome and Firefox still parse non-special URLs as not having a host at all, so I'm not sure if this should be a concern. 

I got stuck when trying to update the opaque-host-parser:

- Should `new URL ('sc://a\x01b')` fail, or should it normalise to `sc://a%01b`? 
  Note that `new URL ('sc://a\x00b')` and `new URL ('sc://a b')` do fail. I think we should prefer a consistent solution. 

- The second question I had is if the host setter should maybe be more liberal about this than the parser. 
  One can fail on `new URL ('sc://a b')` but allow `nonspecialUrl.host = 'a b'` by percent-encoding the space, and similarily the other forbidden codepoints.

**Comment by annevk** [comment]
It should be a concern, because it would make them even less backwards compatible. Which makes it less likely they can adopt the better approach.

I don't think we should change the opaque-host parser from what it does now. This change is not about that.

As for the setter, that also seems like a separate discussion. Unless there's a compelling use case I don't really see the need personally.

**Comment by alwinb** [comment]
Ok, but I woudn't say this is off topic, the definition is used in the opaque-host-parser. 

There have been other, more recent additions to the forbidden-host-codepoints over time, such as `<`, `|`, `>`, and `^` that have also affected opaque-hosts and caused more of them to fail. 

> It should be a concern, because it would make them even less backwards compatible.

In that case, how about percent-encoding the forbidden-host-codepoints (minus `%`) in opaque hosts rather than failing on them? Then Chrome and Firefox would agree with the standard at least on the href of the affected URLs.

Otherwise, the forbidden-host-codepoints can be replaced with separate forbidden-domain-codepoint and forbidden-opaque-host-codepoint sets.

**Comment by achristensen07** [comment]
That sounds great to me

**Comment by TimothyGu** [comment]
@alwinb The idea sounds good to me as well. It will help make opaque host parsing more consistent.

**Comment by karwa** [comment]
+1 to all of:

- Expanding forbidden host code-points for domains. 
   It's strange that we allow as many characters as we do (like `!`, `$`, `(` and `)`), but I appreciate that web compatibility sometimes means allowing strange things 😄 

- Splitting forbidden host code-points for domains and opaque hosts. 
   The standard says "Typically a host serves as a network address, but it is sometimes used as opaque identifier in URLs where a network address is not necessary." It seems wrong to artificially limit what those opaque identifiers may contain and require that users accurately percent-encode them, even when they're not ambiguous.

- (Making the hostname setter more lenient. Not part of this issue, but @alwinb mentioned it and I support it).
   Typically, the setters will percent-encode forbidden characters for you. `hostname` stands alone in being far stricter and requiring the new value is perfectly encoded, else the operation fails. Since this is exposed in the JavaScript API, we could be more consistent and lenient and just do what the developer clearly intended by invoking the setter with a given value.

**Comment by alwinb** [comment]
Continuing the discussion here; maybe I was too quick to do a PR. 

FWIW. I really dislike the idea of failing on a different set of codepoints in opaque-hosts than in domains. 
It would introduce an inconsistency for no good reason. 

My understanding of the argument for doing that, is that otherwise the standard fails on more inputs than before, where Chrome, Firefox and other implementations do not fail.

Βut the argument to not include the controls applies to the other code points as well. 
Firefox and Chrome parse opaque hosts as a path component and they do not fail on any codepoint.

I can see no reason for failing on the exact current set of forbidden-host-codepoints in opaque-hosts, other than to maintain consistency with domains, but that consistency then will be broken.

I do think turning to percent-encoding of opaque hosts is a good solution, and it affects the same few lines in the standard.

**Comment by achristensen07** [comment]
I think there is a consensus that the forbidden host code points should include all C0 controls and U+007F, and that now matches the behavior of all browsers. Let's make that change to the specification and then make a separate issue about what we want to do with opaque hosts, where there is less consensus and less spec compliance.
