### ISSUE TITLE
Inconsistency between Chrome vs Node.js parsing

### ISSUE THREAD

**Issue by char0n** [whatwg/url#677]
Hello all,

I'm not sure this is the right place to report this, but I found an inconsistent behavior of URL constructor in different environments.

Given following construction:

```js
new URL('', 'resolve://')
```

Here is what happens in different environments I tested:

| Env   |     Behavior      |
|----------|:-------------:|
| Google Chrome  96.0.4664.110  |  Throws `VM2548:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL` |
| Firefox 95.0 (64-bit) | parses successfully |
| Node.js >= 12.20.x | parses successfully |

Node.js actually has a documentation section where it gives guide lines how to port `url.resolve` into WHATWG URL. This example is using `resolve://` protocol. I do have an isomorphic needs (running the same code in browser and Node.js) and this inconsistency is causing very nasty bugs in Chrome. Not sure what other browsers are affected.

**Comment by domenic** [comment]
Yep, this is a known Chrome bug. https://jsdom.github.io/whatwg-url/#url=&base=cmVzb2x2ZTovLw== shows how the spec expects this to match Firefox/Node behavior.

You can follow the general project of aligning Chrome with the URL Standard at https://bugs.chromium.org/p/chromium/issues/detail?id=660384 ; I suspect this issue is https://bugs.chromium.org/p/chromium/issues/detail?id=869291

I'll close this since the correct place to discuss implementation bugs is the Chromium issue tracker.

**Comment by domenic** [comment]
> https://jsdom.github.io/whatwg-url/#url=&base=cmVzb2x2ZTovLw== shows how the spec expects this to resolve.

Hmm, I think live URL viewer doesn't like empty strings for `#url`, so that link won't work. But you can input your values into https://jsdom.github.io/whatwg-url/ manually to see the results.

**Comment by char0n** [comment]
THanks for all the links!
