### ISSUE TITLE
Opaque hosts: realistic examples and origins?

### ISSUE THREAD

**Issue by domenic** [whatwg/url#690]
What are some realistic examples of URLs that use [opaque hosts](https://url.spec.whatwg.org/#opaque-host)? I.e., nonempty strings that are not domains or IP addresses, but appear in the host position. The spec doesn't seem to contain any. An artificial example might be something like `my-scheme://opaque-string/path`, but I'm unaware of what kind of protocols might use this in the wild. If any exist, it'd be good to document them in the spec!

We thought they might be useful for cases where we want to define a new kind of resource, where relative URL resolution works. E.g., `isolated-app://app-id/path`, where `app-id` is an opaque host. However, when we went down this route, we discovered a second problem, which is that [origin computation](https://url.spec.whatwg.org/#concept-url-origin) works poorly for such hosts: they always result in an opaque origin. It would be better if it returned something of the form ("isolated-app", "app-id", null, null), so that such "isolated-app" cases were cross-origin from each other, and cross-origin from all HTTP(S) origins, but had same-origin relationships within each other.

This issue in general feels like it falls into the gray area where the URL Standard is trying to provide a general framework, but is primarily focused around the needs of the web and the rest of the web spec ecosystem. That is, nothing in any web specs seems to use opaque-host URLs, so they are getting mixed support in the URL Standard. One resolution would be to say that anything which wants to use opaque-host URLs will need to use its own non-URL-Standard origin computation, but that is a bit subpar, as for example it would lead to `(new URL("isolated-app://app-id/")).origin` differing in value between environments. I guess it's a question about whether origins are a URL concept or a HTML/Fetch concept, which has always been a bit fuzzy.

**Comment by karwa** [comment]
Origins are kind of interesting, and I've been meaning to bring up this whole idea of opaque origins for a while. I did a bit of research on it because the current specification doesn't make a lot of sense and seems to miss some trends which could simplify the model.

> I guess it's a question about whether origins are a URL concept or a HTML/Fetch concept, which has always been a bit fuzzy

I wish I could give some citations, but it's been a while and I can't find everything right now. Basically, the key impression I was left with is that an origin is **not** a property _of a URL_ (like, say, the `scheme`, `path`, and `query` are); it is an abstract domain of trust, which can sometimes be computed _from a URL_ based on what you know about how that URL will be processed.

If the URL has a scheme known to the standard (like HTTP), then we know the host is a domain/IP address, and we know that the host establishes an authority context over the resources accessible via different paths and queries, which are the salient properties of HTTP-family URLs. So there is an obvious domain of trust we can establish, just by looking at the address of the resource and nothing else.

For things like `file:` URLs, the way in which the address maps to an authority context is less obvious. You could imagine that user-defined subtrees of the filesystem might be isolated from one another in some fashion, so my top-secret strategy documents can include resources (including executable code/scripts) from other local files, and they will belong to different domains of trust and be isolated from each other as cross-origin resources typically are.

> One resolution would be to say that anything which wants to use opaque-host URLs will need to use its own non-URL-Standard origin computation, but that is a bit subpar, as for example it would lead to (new URL("isolated-app://app-id/")).origin differing in value between environments.

Along the same lines as I was mentioning above - for URLs not known to the standard, there is no way to reasonably establish a guaranteed realm of trust that is both permissive enough to be useful and strict enough to be secure, and which works for every possible URL scheme. For those situations, applications must invent their own origin-like abstractions based on their knowledge of the schemes they work with. This is what I advise in Swift, using our `enum`-with-payload feature to model a discriminated union:

```swift
enum SecurityDomain {

  /// Security domain is 'obvious' due to URL scheme
  /// being known by the standard.
  case derivedFromURL(WebURL.Origin)

  /// A security domain which has been established
  /// by application-specific logic.
  case applicationDefined(MyApp.RealmOfTrust)

  /// Opaque origin, unable to determine a security domain.
  /// These must be maximally isolated from each other.
  case undefinedOpaque

  /// Checks whether two security domains are considered equivalent.
  static func == (lhs: Self, rhs: Self) -> Bool {
    switch (lhs, rhs) {
    case (.derivedFromURL(let lhsOrigin), .derivedFromURL(let rhsOrigin)):
      return lhsOrigin == rhsOrigin
    case (.applicationDefined(let lhsRealm), .applicationDefined(let rhsRealm)):
      return lhsRealm == rhsRealm
    default:
      return false
    }
  }
}
```

I actually think that HTML should do the same thing. But to explain why, a bit of background:

Currently, the definition of opaque origins means that calculating an opaque origin is the same as creating a new origin. This leads to URL libraries representing opaque origins as UUIDs/nonces/atomic counters internally:

- [`servo/rust-url`](https://github.com/servo/rust-url/blob/48fcbe1c543a8350a74b226c17c1ec06c6e19a68/url/src/origin.rs#L64-L65)
- [`chromium/GURL`](https://github.com/chromium/chromium/blob/fd8a8914ca0183f0add65ae55f04e287543c7d4a/url/origin.h#L91-L97)
- I think [gecko does something similar](https://github.com/mozilla/gecko-dev/blob/cefe3965912a9fd75e0f7d39642dddf1e52e2142/netwerk/base/mozurl/src/lib.rs#L307), although I'm not an expert at that codebase (or the others, to be fair).

It has this really weird property that if you calculate a URL's origin, that particular local variable in code will compare as same-origin with itself, but calculating the URL's origin _again_ produces a different opaque origin. It doesn't really make any sense - if an origin has to do with a resource's _security context_, why does it matter when I calculate it?

Why is calculating the domain of trust the same as creating a new domain of trust?

Really, if we want to express that these are _undefined_ security domains and should be maximally-isolated, they should behave like floating point `NaN` values, where `x == x` can return `false`, even for a local variable. They should not be same-origin with anything at all.

But this would break HTML, which actually relies on this quirk. It calculates opaque origins at particular times, saying things like:

> Let navigationParams be a new navigation params whose request is null, response is null, **origin is a new opaque origin**, ...

And then it will rely on those details later by saying:

> Two origins, A and B, are said to be same origin if the following algorithm returns true:
> - If A and B **are the same opaque origin**, then return true.

Really, when HTML deliberately calculates new opaque origins, it is establishing new domains of trust for a particular operation or browsing context, and it should be more explicit about that, instead of making it part of the opaque origin concept.

I think that would actually help opaque origins become more useful, and give a firmer grounding to application/context-specific security domains which can be computed (perhaps only partially) from a URL but are not defined by the URL standard.

**Comment by domenic** [comment]
> I wish I could give some citations, but it's been a while and I can't find everything right now. Basically, the key impression I was left with is that an origin is not a property of a URL (like, say, the scheme, path, and query are); it is an abstract domain of trust, which can sometimes be computed from a URL based on what you know about how that URL will be processed.

I agree with this.

The problem is that computing an origin from a URL is key for Fetch to determine whether a given fetch will be cross-origin or same-origin. So that computation-from-URL mapping needs to be defined somewhere that can be shared by at least Fetch and HTML, and URL seems like the place it's ended up.

> It has this really weird property that if you calculate a URL's origin, that particular local variable in code will compare as same-origin with itself, but calculating the URL's origin again produces a different opaque origin. It doesn't really make any sense - if an origin has to do with a resource's security context, why does it matter when I calculate it?

I think you're right, this is weird. In practice I think opaque origins computed from URLs are just not used on the web platform, or at least, not in a context where they're ever expected to return true in an equality comparison.

However, opaque origins for other objects (e.g. `Document`s) often do need to compare equal to themselves. I think the current model works fine there, but perhaps it's just obvious to me that minting a new opaque origin and associating it with a `Document` is minting a new security context.

---

To try to bring things back to opaque hosts, the problem is we don't really want to create a new origin-like abstraction. We want to create a new scheme which uses opaque hosts, but with origin computation that makes everything under `isolated-app://my-app-id/` same-origin for purposes like HTML (including cross-origin object checks) and Fetch (including CORS). I guess this issue is complaining that we'd have to change origin computation when we did so, whereas we were hoping we could just use the nice "unknown scheme -> opaque host" pathway that's in the URL Standard already. But perhaps updating origin computation is unavoidable and a fine price to pay.

**Comment by karwa** [comment]
> To try to bring things back to opaque hosts, the problem is we don't really want to create a new origin-like abstraction. We want to create a new scheme which uses opaque hosts, but with origin computation that makes everything under isolated-app://my-app-id/ same-origin for purposes like HTML (including cross-origin object checks) and Fetch (including CORS).

You could do that; you just need to figure out a way to plug-in to HTML and Fetch's application-specific security context calculation.

Basically, I think the model should be (or really, de-facto already is):

1 - Check to see if the scheme is known to the standard. Yes? -> Tuple origin. No? Continue.

2 - Application-defined heuristics to try establish a security context, perhaps calling registered callbacks, reading a manifest or configuration file, or just generating a unique ID (as HTML does). If it can establish a context -> Custom origin. Nothing? Continue.

3 - For everything that doesn't fit within an island of trust, you have to assume maximum isolation.

One other thing you would have to consider: opaque hosts are not interpreted at the same level that HTTP hosts are, so they wouldn't get things like percent-decoding, IDNA mappings, Unicode normalization, or normalized IPv4 addresses. This would affect equality operations and questions of same-origin, but maybe it's okay to opt-out of those and require literal hostname equivalence.

**Comment by annevk** [comment]
Some thoughts:

* I think a more ideal layering would probably move origin completely out of URL and have an API for it that throws on unknown schemes, which would make extensions a little safer.
* For new schemes it very much depends how we compute the origin, see `blob:` URLs for a good example of that. So I don't think we can have a general rule.
* If we add a new scheme to the web platform, I would expect us to make changes similar to how we did for `blob:` URLs.
* Computing new opaque origins from URLs is important for HTML too if I remember correctly. If two nested documents navigate to the same `data:` URL, they should not end up sharing an origin and I think today that is the result of the URL->origin mapping. Of course, you could envision not relying on a URL->origin mapping here, but instead HTML special casing `data:` URLs. However, I think it is more generally sound that two such identical URLs do not share an authority. (I.e., I do think this makes sense, contrary to what @karwa said above.)

Changes we could make to slightly improve the setup:

* Perhaps we can change the API such that the `origin` member is not exposed outside of browsers somehow. I'm not sure how that would work given `Exposed=*`, but having something for (at least) Deno and Node.js came up before.
* We could move origin computation elsewhere, but the API will continue to rely on it. This might strengthen the above point even further.

**Comment by karwa** [comment]
> Computing new opaque origins from URLs is important for HTML too if I remember correctly. If two nested documents navigate to the same data: URL, they should not end up sharing an origin and I think today that is the result of the URL->origin mapping. Of course, you could envision not relying on a URL->origin mapping here, but instead HTML special casing data: URLs. However, I think it is more generally sound that two such identical URLs do not share an authority. (I.e., I do think this makes sense, contrary to what @karwa said above.)

Just to be clear: I **do** think it makes sense for two nested documents to the same `data:` URL to not share an authority.

The thing that doesn't make sense is that there is a concept of having the "same opaque origin". Opaque origins mean we don't know what the origin is (the URL scheme is not known), so we can't really call them the same as anything. Currently, we have this concept of a 'new' opaque origin, with an identity and security domain established when you compute them.

```swift
// Each call to 'url.origin' returns a 'new' opaque origin.

let url = URL("non-special://somehost/path")
url.origin.isSameOrigin(as: url.origin) // false - i.e. no shared authority, isolated from itself.

// But if we store it in a variable, we create a security domain out of thin air
// at this point in the code. The opaque origin actually compares as same-origin
// with something now!

let savedOrigin = url.origin
savedOrigin.isSameOrigin(as: url.origin) // false, as expected.

savedOrigin.isSameOrigin(as: savedOrigin) // true!! when did we get an authority?
```

This is a consequence of the definitions in the HTML and URL Standards.

What I think should happen instead is that, when a nested document navigates to a `data:` URL, the HTML standard, rather than saying to return a "new opaque origin", would have 2 choices:

- Explicitly say to generate a unique token to serve as the origin for that document (in lieu of one from the URL), if there is some meaningful identity to assign to it. This would match the current behaviour of opaque origins.
- Leave the origin unspecified, for maximum isolation. Considering the example above, this would fix the issue and make `savedOrigin.isSameOrigin(as: savedOrigin)` return `false`, like a floating point NaN returns `x == x` as `false`.

The former would be a sort-of "HTML extension" so to speak, defining contextually relevant zones of trust based on its task of expressing rich, interlinked documents. Those zones of trust based on generated unique identifiers may not be meaningful in other contexts.

**Comment by domenic** [comment]
Does anyone have any examples of opaque-host URLs in the wild?

**Comment by annevk** [comment]
@karwa same opaque origin becomes relevant if the `data:` URL document creates a `blob:` URL worker. The `data:` URL and the `blob:` URL will share an origin (and authority) in that case. You could special case a bunch of things throughout, but I think the current setup is actually quite nice.

@domenic according to https://en.wikipedia.org/wiki/List_of_URI_schemes there are a number of them. Don't think any are in browsers, except for maybe `web+` and such? For a moment I thought `stun:` and `turn:`, but those end up with paths similar to `blob:` URLs.

**Comment by domenic** [comment]
Perfect, I should have thought of looking there. Probably the most common is `git://github.com/user/project-name.git`. I'll try to send a PR adding that example to the spec somewhere, since otherwise the opaque host concept was a bit too alien for me to grasp.
