### ISSUE TITLE
Should we ignore IPv6 zone identifiers when parsing a URL?

### ISSUE THREAD

**Issue by valenting** [whatwg/url#742]
The consensus of #392 was that browsers don't want to support  IPv6 zone identifiers.

One possible path forward would be ignoring the zone identifier when parsing the URL, but as [Anne points out](https://github.com/whatwg/url/issues/392#issuecomment-1396750341):
> If it should impact authority and we end up treating multiple distinct authorities as one, that would not be good. And while there are plenty of ways to make a URL appear like another one, I'm not sure we want to add to that problem.
> Also in other domains ignoring all input after a certain character has led to injection attacks. How would we avoid those here?

Right, I think the injection attack issue is worth exploring. In that case we probably also need to check that all of the characters in the zoneID are in the unreserved character set.

**Comment by annevk** [comment]
cc @martinthomson @mnot

**Comment by mnot** [comment]
Not sure - why am I CC:ed?

**Comment by martinthomson** [comment]
(I also don't know why Mark was cc'd.)

I was originally of the view that perhaps it would be mostly harmless to ignore a zone identifier, but I think that Anne just set out a pretty cogent argument why mostly != totally.  Maybe that gap can be closed though.

Attacks like this tend to occur as identifiers traverse more elements.  If browsers were to strip stuff out before presenting them in any way (in UI, through the DOM, or to the network), then the risk is mostly limited to any processing that occurs server-side.  That's maybe enough to put an end to this idea, but it is not the same as maybe having this shown in the address bar.  In any case, that was my thinking.

**Comment by annevk** [comment]
@mnot I figured you'd be interested in a change of this magnitude, if it were to happen.

As an example, `http://[::1%32]/` is currently failure per the URL Standard (and Gecko & WebKit), but `http://[::12]/` in Chromium. After the proposed change it would be `http://[[::1]/`. I'd rather align on failure.

As I understand it the use case for ignoring it is that sometimes you might happen across a URL (such as with a printer) and the zone ID doesn't matter because the default zone also works. How common is that for most end users?

**Comment by mnot** [comment]
Things that have meaning (to some) being swallowed silently makes me nervous -- I think I agree with you @annevk that failure is the better option.

**Comment by martinthomson** [comment]
> As I understand it the use case for ignoring it is that sometimes you might happen across a URL (such as with a printer) and the zone ID doesn't matter because the default zone also works. How common is that for most end users?

The default zone working seems pretty likely.  Though the usage of zone identifiers in URLs likely approaches zero (yes, in part due to browsers not supporting them), it would be very rare for the same IPv6 address to be assigned to different hosts and for those two hosts to be attached to different interfaces on the same machine.

The most likely scenario is where there are site- or link-local addresses that collide. And when I say "most likely", it takes a LOT of hosts (>2<sup>32</sup>) on the two attached networks before the probability of a collision becomes non-trivial.

That erasure is very likely to work is why we entertained it.  But @annevk's point about various types of request smuggling ("`https://[x::y2]/` is forbidden, but `https://[x::y%32]` is OK because "x::y" is OK" .. or vice versa) make me think that it is easier to generate an error and be done.

**Comment by valenting** [comment]
> As an example, `http://[::1%32]/` is currently failure per the URL Standard (and Gecko & WebKit), but `http://[::12]/` in Chromium. After the proposed change it would be `http://[[::1]/`. I'd rather align on failure.

This seems like a bug in Chromium. They shouldn't be doing percent decoding before invoking the IPv6 parser.

**Comment by annevk** [comment]
(Yeah, https://github.com/web-platform-tests/wpt/pull/38034 covers that.)

**Comment by annevk** [comment]
@valenting I'm inclined to close this. OP doesn't really present a compelling story as to why we would want to add this complexity.
