### ISSUE TITLE
Percent-decode more stuff?

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#87]
In https://github.com/whatwg/url/issues/77, I was surprised that `.` was such a special case. It is indeed in Firefox 44, but in Chromium 48 other characters are also percent-decoded: `-`, `_`, `~`, and ASCII alpha-numerics. (I don’t have other browsers to test right now.)

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=3878

It may be worth testing other URL components too.

**Comment by annevk** [comment]
I think it's a special case in most browsers from when I tested this last time around.

**Comment by annevk** [comment]
@achristensen07 what are your ideas here? I believe @valenting wanted to do more decoding in Gecko as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1197123.

It's basically a choice between this document, Safari, and Firefox and Chrome and Edge. Arguably what Chrome and Edge do is somewhat nicer since there is more canonicalization, but it could lead to subtle issues too.

**Comment by achristensen07** [comment]
I think I'm opposed to this change.  alert(new URL("http://host/p%61th")); should show the %61, not 'a'.  There are a lot of URL implementations based on old RFCs, and we should try to match their behavior as closely as possible.  People sometimes want '%' in the path and often in the query, and we don't want people to have to put things like "%2525" in their URL for some user agents and not others.

**Comment by annevk** [comment]
@achristensen07 note that the old RFCs encourage normalizing these in the second paragraph of https://tools.ietf.org/html/rfc3986#section-2.3.

**Comment by annevk** [comment]
To be clear, not %25, but a lot of other ranges, including %61.

**Comment by achristensen07** [comment]
Sure enough, Chrome and Edge percent decode more things in the path, but not the query.  This can bee seen with alert(new URL("http://host/%45%25?%45%25")); We definitely shouldn't touch the query and all browsers seem to agree on this.
I disagree with this proposal and rfc3986 because I think a canonicalized URL should always be untouched when reparsed.  With this proposal, "http://host/%%36%31" would be canonicalized to "http://host/%61" which when reparsed would become "http://host/a" which is bad.  Right now Chrome percent-encodes the first '%' in "http://host/%%36%31" which is strange, and Edge throws an exception.
It is clear that something needs to change and that we need to unite behavior.  Right now, it is impossible to send "GET /%2e HTTP/1.1" as the first line of an HTTP request and I think that also needs to change.  I'm not sure what the solution should be, but percent-decoding more characters isn't it.

**Comment by annevk** [comment]
Paging @foolip to see if we can get Chrome's perspective on this.

**Comment by annevk** [comment]
@valenting I suggest that before changing Gecko here we try to bring this thread to a conclusion first.

**Comment by achristensen07** [comment]
Is it common on the internet to see percent-encoded dots or other characters in the path?  Why was section 2.3 added to rfc3986? Safari has not percent-decoded anything in the path, and I'm not aware of any compatibility issues, but it's possible I've missed something.  A solution to this problem would be to just not percent-decode anything in the path, including %2e and %2E

**Comment by gibson042** [comment]
Question: to which of the following should "http://host/%%36%31" be equivalent?
* "http://host/%2561" (representing the non-decodable percent as a percent and recovering immediately)
* "http://host/%25%25361" (representing the non-decodable percent as a percent and recovering _after_ the character responsible for its non-decodability)
* "http://host/%25%2536%2531" (giving up on percent decoding completely upon encountering a non-decodable percent)
* nothing (it is invalid, as in the older RFCs)
* other (e.g., "http://host/a") (please no)

**Comment by achristensen07** [comment]
Safari and Firefox both leave "http://host/%%36%31" untouched when canonicalizing.  They also agree on the behavior of URLs like "http://host/%2e" and I suggest we change the spec to match this.  What is the rationale behind Chrome's percent-encoding only the first percent, and percent decoding some characters but not others?  It leads to some confusing behavior.

**Comment by valenting** [comment]
> They also agree on the behavior of URLs like "http://host/%2e" and I suggest we change the spec to match this.
We actually tried to change it in Firefox so that we decode %2e but it got backed out due to an implementation bug. :)

**Comment by achristensen07** [comment]
I still think we should change the spec to not percent-decode anything in the path.  Percent-decoding %2E makes it so there is only one thing that cannot be in the path.  Percent-decoding more leads to strange reparsing behavior.  Simpler is better, unless there's a good reason we need this.

**Comment by annevk** [comment]
I don't understand. When I try `(new URL("https://example/%2e/test"))` I get `https://example/test` in Firefox (Nightly).

**Comment by annevk** [comment]
And not normalizing that seems dangerous for servers, since you might be able to trick the server to go outside the root of the site.

**Comment by valenting** [comment]
The bug was about %2e%2e%2e - or %2eX we don't normalize that.

**Comment by achristensen07** [comment]
What if we kept the definition of double-dot path segments to protect servers and maybe single-dot path segments, but removed this:
`If c is "%" and remaining, ASCII lowercased starts with "2e", append "." to buffer and increase pointer by two.`

**Comment by annevk** [comment]
Yeah, that could work. I'd still really like to hear from @sleevi / @foolip.

**Comment by foolip** [comment]
I don't know Blink's KURL or what lies beneath well enough to judge what that change might mean. @sleevi?

Tests that exercise the difference might be useful, if they'd go from pass to fail or vice versa in Chrome it should be easier to understand where to look. https://github.com/w3c/web-platform-tests/tree/master/url is the right place I guess?

**Comment by annevk** [comment]
@foolip yes.

**Comment by gibson042** [comment]
> Safari and Firefox both leave "http://host/%%36%31" untouched when canonicalizing.

And therefore equivalent to "http://host/%25%2536%2531", right?

**Comment by achristensen07** [comment]
No, none of those percents are encoded or decoded. 

Also, I don't think it is adequate to protect servers by relying on the client getting rid of %2e%2e in the path. A server should have to protect itself from requests for ../../../etc. even from malicious clients that do not obey the URL spec. I don't see how parsing %2e%2e as .. protects servers.

**Comment by annevk** [comment]
@achristensen07 you cannot craft malicious requests like that from a browser (and therefore with the user's credentials).

**Comment by sleevi** [comment]
@annevk Sorry for the delay. The rationale for Chrome's current behaviour is, I believe, captured here in this comment block - https://cs.chromium.org/chromium/src/url/url_canon_path.cc?rcl=0&l=167

The reason for that change is explained in https://chromium.googlesource.com/chromium/src/+/6982036dc15ba85cdbf7339265f030ff7582ff3b - and the related crash.

So there are definitely implications to changing Chrome that make it harder to be an easy flip, but it's not to say it's unreasonable to explore changing.

**Comment by gibson042** [comment]
> No, none of those percents are encoded or decoded.

This project claims an explicit goal of replacing RFC 3986 and RFC 3987 by aligning with contemporary implementations, presumably affecting both clients and servers as those documents do. And since percent-decoding is already specified, "http://host/%36%31" is equivalent to "http://host/61". The question is what equivalence class (if any) "http://host/%%36%31" falls into (e.g., Chrome treats it as equivalent to "http://host/%2561", one option of at least [four](https://github.com/whatwg/url/issues/87#issuecomment-255510163)).

**Comment by annevk** [comment]
@gibson042 percent-decoding is not specified by the URL Standard. Replacing those RFCs does not mean that we'll prescribe what they prescribe.

**Comment by annevk** [comment]
It seems we avoid most issues here by simply not percent-decoding (other than host, where a one-time decode pass followed by IDNA is fine as it will return failure if anything fails).

My conclusion here is to embrace the suggestion in https://github.com/whatwg/url/issues/87#issuecomment-256124153 to only work with double-dot path segments and single-dot path segments and not decode %2e generally (or anything else).

We need to make sure that is covered by the testsuite.

Gecko will need to WONTFIX https://bugzilla.mozilla.org/show_bug.cgi?id=1197123 (action item for @valenting I think).

Chrome and Edge will have to change their behavior. I think in the end that will turn out to be a drastic code simplification for them since they no longer have to worry about cases such as `%%300`.

**Comment by gibson042** [comment]
@annevk: Servers absolutely follow https://tools.ietf.org/html/rfc3986#section-6.2.2.2 , serving `foo.ext` in response to `GET /%66%6f%6f.ext`.

**Comment by annevk** [comment]
Sure, and I would expect them to. But the mapping of an HTTP request to a resource on disk is not exactly governed by the URL Standard. How servers deal with URLs and what amount of normalization they apply is very much up to them.

**Comment by gibson042** [comment]
So to be clear, you are in favor of eliminating [percent-encoding normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.2) (at least outside the authority component) and defining `/%66%6f%6f.ext` and `/foo.ext` as distinct? But presumably preserving percent-encoding case normalization, so `/%66%6f%6f.ext` and `/%66%6F%6F.ext` are equivalent?

**Comment by annevk** [comment]
@gibson042 there's different components here that can do different things.

What I'm favor of is that clients do not normalize and treat your given examples as distinct. This follows from how we define the URL parser and then pass the URL to the networking subsystem, etc.

A server however can still see those paths and treat them as equivalent. That would be up to the server library that maps paths to resources. I don't think we have to take a stance on whether such mapping takes place in the URL Standard.

**Comment by gibson042** [comment]
@annevk: It seems to me like you MUST take such a stance for ensuring interoperability—defining a percent-encoding mechanism without defining a percent-decoding normalization is begging for problems. RFC 3986 avoids them by requiring "%" to be followed by a pair of hexadecimal digits (allowing decoding of every "%" after splitting on separators), but what you're proposing would permit compliant proxies that equate "/-" vs. "/%2D" vs. "/%2d" (i.e., the proxies that already exist) to thwart _also_-compliant servers that do not.

It'd be like ECMAScript engines disagreeing on whether `"A"`, `"\x41"`, and `"\u0041"` represent the same string, or some accepting `"\"` as `"\\"`.

**Comment by sleevi** [comment]
Right, I think it's unlikely that we would be implement those changes in Chrome, given present implementation considerations, for the reasons that @gibson042 raises. At least with respect to Chrome's implementation, a variety of reasons have us wanting to ensure a consistent internal canonicalization, which I think is somewhat at odds with the suggestion that the API perform no normalization, because at some point, the API will transit a component in Chrome that requires canonicalization. So, to the extent possible, I'd like to see if we can ensure a consistent canonicalization across implementations, since such canonicalization fundamentally gets exposed via the API.

**Comment by annevk** [comment]
@sleevi I'm not sure I follow. If there's no normalization during parsing, there's no normalization in the model, and there's no normalization exposed in the API. Where do you think normalization would happen?

**Comment by sleevi** [comment]
@annevk I'm suggesting that normalization is an intrinsic necessity of Chrome, at present, and as such, ends up reflected in the API we surface. While it's possible to suggest that's changable, it's not currently a high priority - that is, the normalization that occurs is an intrinsic dependency of many of Chromium's URL-handling subsystems. If we change the parsing phases to remove normalization, this creates more issues than it solves. Put differently, if normalization is removed, it's unlikely Chromium will be able to align on this point in any reasonable timeframe.

**Comment by annevk** [comment]
@sleevi could you perhaps explain why it's an intrinsic necessity in some detail? And I guess also, what exactly the normalization entails?

**Comment by sleevi** [comment]
@annevk It's important to understand, as mentioned before, that our URL code is shared across a variety of Google client platforms, and, even within Chrome, shared through a variety of layers - IPC, networking, UI (and, of that, security UI as a distinct subset), and of course, the web-visible exposure provided by the URL API.

While the URL API itself has no intrinsic needs that we're immediately aware of (short of checking compat issues), what is essential for a variety of checks and comparisons is that we have a consistent set of behaviours and presentations for URLs, and that inherently necessitates normalization, such that any two URLs, if they represent the same underlying URL, are treated equivalently. This behaviour has been extensively integrated into our code, because it was one of the motivations for the library itself.

Again, that's not to say we can't change, but it's certainly not a priority, given how significant an undertaking it would be. I think @gibson042's concerns are reasonable, and I suspect that many web developers would be surprised. I have trouble accepting @achristensen07's arguments against it.

To put the counter-argument forward: Why do you feel that normalization would be bad?

**Comment by annevk** [comment]
I'm not necessarily opposed, if we can find a reasonable processing model that everyone can agree on and doesn't lead to subtle issues with input such as `%%300`. I'm just trying to explore options.

And note that the URL API is not the only bit that's web-visible. HTTP requests, `<a>`, `location`, etc. are all part of the equation.

**Comment by annevk** [comment]
I think for now I'm proceeding with the plan on aligning the standard with what Firefox and Safari implement.

We don't have a credible alternative proposal and the current document is aligned with nobody.

And while RFC3986 does allow for additional normalization, it doesn't prescribe it, so I think either way we're roughly aligned with that. We could mention explicitly that servers are allowed to perform additional normalization and maybe should do that at some point. Or even expose an API to clients.
